name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
    
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Create screenshots directory
      run: mkdir -p screenshots

    - name: Run Playwright tests
      run: |
        npx playwright test --workers=5 \
          --project=chromium \
          --reporter=html,line \
          --retries=2 \
          --timeout=100000
      env:
        HEADLESS: false
        SLOW_MO: 1000

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
          screenshots/
        retention-days: 7

    - name: Upload screenshots
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: visual-regression-screenshots
        path: screenshots/
        retention-days: 7
