name: Run Playwright tests

on:
  schedule:
    - cron: '30 3 * * 1-5' # 9:00 AM IST on weekdays
  workflow_dispatch:

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        shardTotal: [10]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run tests
        run: npm run test:chrome -- --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: Upload blob report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-blob-report-${{ matrix.shardIndex }}
          path: ./blob-report
          retention-days: 1

      - name: Upload .temp folder (only on shard 1)
        if: ${{ matrix.shardIndex == 1 && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: temp-folder
          path: ./.temp

  merge-reports:
    name: Merge Reports
    needs: [run-tests]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Download blob reports
        uses: actions/download-artifact@v4
        with:
          path: ./all-reports
          pattern: '*-blob-report-*'
          merge-multiple: true

      - name: Download .temp folder
        uses: actions/download-artifact@v4
        with:
          name: temp-folder
          path: ./.temp

      - name: List .temp folder content
        run: ls -R ./.temp || echo ".temp folder not found!"

      - name: Run mergeTestData
        run: npx ts-node ./dataClenUpScripts/mergeTestData.ts
